---

# @see https://github.com/F5Networks/f5-ansible/issues/32

- name: Create pool
  bigip_pool:
      name: "mypool"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"

- name: Create virtual server
  bigip_virtual_server:
      name: "myvip"
      destination: "1.1.1.1"
      port: 80
      pool: "mypool"
      snat: "Automap"
      description: "My VIP"
      all_profiles:
          - tcp
          - http
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Create virtual server
  assert:
      that:
          - result|changed

- name: Create virtual server - Idempotent check
  bigip_virtual_server:
      name: "myvip"
      destination: "1.1.1.1"
      port: 80
      pool: "mypool"
      snat: "Automap"
      description: "My VIP"
      all_profiles:
          - tcp
          - http
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Create virtual server - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete virtual server
  bigip_virtual_server:
      destination: "1.1.1.1"
      name: "myvip"
      partition: "{{ bigip_partition }}"
      password: "{{ bigip_password }}"
      port: 80
      pool: "mypool"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"

- name: Delete pool
  bigip_pool:
      name: "test_pool"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Delete pool
  assert:
      that:
          - result|changed